version: '3'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: babydataapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin12345

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    command: sh -c "python manage.py migrate && waitress-serve --listen=*:8000 BabyDataProject.wsgi.application"
    volumes:
      - .:/babydataproject
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_ALLOWED_HOSTS=0.0.0.0,localhost,127.0.0.1

volumes:
  postgres_data: