# Generated by Django 5.1.1 on 2024-12-15 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0003_baby_created_at_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyEvent',
            fields=[
                ('baby_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='babyapp.baby')),
                ('diaper_change', models.BooleanField(default=False)),
                ('dirty_diaper', models.BooleanField(default=False)),
                ('meal', models.CharField(max_length=100)),
                ('sleep', models.DurationField()),
            ],
            bases=('babyapp.baby',),
        ),
        migrations.RenameField(
            model_name='baby',
            old_name='created_at',
            new_name='created_at_time',
        ),
    ]
