# Generated by Django 5.1.1 on 2024-12-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0004_babyevent_rename_created_at_baby_created_at_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babyevent',
            name='dirty_diaper',
        ),
        migrations.AlterField(
            model_name='babyevent',
            name='diaper_change',
            field=models.CharField(max_length=100),
        ),
    ]
