# Generated by Django 5.1.1 on 2024-12-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0005_remove_babyevent_dirty_diaper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyevent',
            name='sleep',
            field=models.CharField(max_length=100),
        ),
    ]
