# Generated by Django 5.1.1 on 2024-12-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyapp', '0007_alter_baby_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyevent',
            name='meds',
            field=models.CharField(default='', max_length=100),
        ),
    ]
